### ISSUE TITLE
Better divisions/products

### ISSUE THREAD

**Issue by artrag** [nanochess/CVBasic#13]
The compiler could improve the generated code for math by supporting shift operations when you multiply/divide by powers of two.
Version 0.70 use generic mul/div functions even when those optimization is possible

**Comment by polluks** [comment]
@artrag Are you sure?
https://github.com/nanochess/CVBasic/blob/a4464d255b7c6c3068fe52440db9fe68604a0fb7/cpuz80.c#L468

**Comment by artrag** [comment]
yes, I get this for frame/16

	; 		call TCOPY($3000 + (12+(FRAME/16 and 3))*32)
	LD HL,(frame)
	LD DE,16
	CALL _div16
	LD A,L
	AND 3
	LD L,A
	LD H,0
	LD DE,12
	ADD HL,DE
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	LD DE,12288
	ADD HL,DE
	CALL TCOPY

**Comment by artrag** [comment]
In attach the complete ASM file where the basic code is in the comments
[output.asm.txt](https://github.com/user-attachments/files/17367478/output.asm.txt)

**Comment by artrag** [comment]
A better conversion would have been 
	; 		call TCOPY($3000 + (12+(FRAME/16 and 3))*32)
	LD HL,(frame)
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	LD A,H
	AND 3
	LD L,A
	LD H,0
	LD DE,12
	ADD HL,DE
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	ADD HL,HL
	LD DE,12288
	ADD HL,DE
	CALL TCOPY

**Comment by artrag** [comment]
An even better conversion, using the fact that the result of the division is AND 3, could have been:

; call TCOPY($3000 + (12+(FRAME/16 and 3))*32)
LD A,(frame)
RRCA
RRCA
RRCA
RRCA
AND 3
ADD A,12
LD L,A
LD H,0
ADD HL,HL
ADD HL,HL
ADD HL,HL
ADD HL,HL
ADD HL,HL
LD DE,12288
ADD HL,DE
CALL TCOPY
