### ISSUE TITLE
undefined instruction errors assembling for creativision

### ISSUE THREAD

**Issue by J03M4N** [nanochess/CVBasic#14]
I'm running windows7
gorilla.bas, demo.bas spaceattack.bas asm files generated by cvbasic for creativision all have "undefined instruction errors" with gasm80 :
Error: Undefined instruction 'BNE.L CV45' at line 3524
Error: Undefined instruction 'BNE.L CV46' at line 3530
Error: Undefined instruction 'BNE.L CV47' at line 3546
Error: Undefined instruction 'BNE.L CV48' at line 3562
Error: Undefined instruction 'BEQ.L CV49' at line 3580
Error: Undefined instruction 'BEQ.L CV50' at line 3609
Error: Undefined instruction 'BNE.L CV53' at line 3676
Error: Undefined instruction 'BNE.L CV55' at line 3685
Error: Undefined instruction 'BNE.L CV56' at line 3694
Error: Undefined instruction 'BNE.L CV59' at line 3721
Error: Undefined instruction 'BNE.L CV61' at line 3732
Error: Undefined instruction 'BNE.L CV62' at line 3743
Error: Undefined instruction 'BCC.L CV63' at line 3747
Error: Undefined instruction 'BCC.L CV65' at line 3769
Error: Undefined instruction 'BCC.L CV67' at line 3807
Error: Undefined instruction 'BCS.L CV68' at line 3842
Error: Undefined instruction 'BCS.L CV69' at line 3862
Error: Undefined instruction 'BNE.L CV70' at line 3880
Error: Undefined instruction 'BNE.L CV71' at line 3887
Error: Undefined instruction 'BNE.L CV72' at line 3894
Error: Undefined instruction 'BEQ.L CV75' at line 3968
Error: Undefined instruction 'BCS.L CV74' at line 4068
lines and lines of these
etc.

Am I doing something wrong?

**Comment by nanochess** [comment]
It looks like a mistake on my side, for some reason the distro for Windows contains an old version of gasm80.

You can compile it from https://github.com/nanochess/gasm80

I'll try to release an updated distro as soon as possible.

**Comment by nanochess** [comment]
I just uploaded a new release here -> https://github.com/nanochess/CVBasic/releases

**Comment by J03M4N** [comment]
Worked! Thank you! Such a cool project.
